[package]
name = "adaptors"
version = "0.1.0"
edition = "2024"

[dependencies]
surf = "2.3.2"
serde = "1.0.216"
serde_repr = "0.1.19"
futures = "0.3.31"
async-trait = "0.1.83"
macro = { path = "../macro" }
